[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Catppuccin colorscheme
repo = 'catppuccin/vim'
name = 'catppuccin'
hook_add = '''
  set termguicolors
  set background=dark
  let g:catppuccin_flavour = "mocha"
  au MyAutoCmd VimEnter * nested colorscheme catppuccin_mocha
  " カラースキーム適用後に透過設定を再適用
  autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=NONE
  autocmd ColorScheme * highlight NonText ctermbg=NONE guibg=NONE
  autocmd ColorScheme * highlight LineNr ctermbg=NONE guibg=NONE
  autocmd ColorScheme * highlight Folded ctermbg=NONE guibg=NONE
  autocmd ColorScheme * highlight EndOfBuffer ctermbg=NONE guibg=NONE
'''

[[plugins]]
repo = 'Shougo/vimfiler'
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'davidoc/taskpaper.vim'
 
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'junegunn/fzf'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]] # vim-airline with catppuccin theme
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'catppuccin_mocha'
  let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes' 
[[plugins]]
repo = 'sheerun/vim-polyglot'
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'junegunn/goyo.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'jiangmiao/auto-pairs'
[[plugins]]
repo ='editorconfig/editorconfig-vim'
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'tpope/vim-markdown'
[[plugins]]
repo = 'iamcco/markdown-preview.vim'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
[[plugins]]
repo = 'mattn/sonictemplate-vim'
[[plugins]]
repo = 'reireias/vim-cheatsheet'
[[plugins]]
repo = 'simeji/winresizer' 
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'previm/previm'
