# Catppuccin Mocha colors for Powerlevel10k
# Based on Catppuccin Mocha palette

# Catppuccin Mocha color definitions
typeset -g POWERLEVEL9K_CATPPUCCIN_ROSEWATER=254
typeset -g POWERLEVEL9K_CATPPUCCIN_FLAMINGO=210
typeset -g POWERLEVEL9K_CATPPUCCIN_PINK=212
typeset -g POWERLEVEL9K_CATPPUCCIN_MAUVE=183
typeset -g POWERLEVEL9K_CATPPUCCIN_RED=210
typeset -g POWERLEVEL9K_CATPPUCCIN_MAROON=174
typeset -g POWERLEVEL9K_CATPPUCCIN_PEACH=216
typeset -g POWERLEVEL9K_CATPPUCCIN_YELLOW=229
typeset -g POWERLEVEL9K_CATPPUCCIN_GREEN=151
typeset -g POWERLEVEL9K_CATPPUCCIN_TEAL=159
typeset -g POWERLEVEL9K_CATPPUCCIN_SKY=153
typeset -g POWERLEVEL9K_CATPPUCCIN_SAPPHIRE=117
typeset -g POWERLEVEL9K_CATPPUCCIN_BLUE=117
typeset -g POWERLEVEL9K_CATPPUCCIN_LAVENDER=183
typeset -g POWERLEVEL9K_CATPPUCCIN_TEXT=189
typeset -g POWERLEVEL9K_CATPPUCCIN_SUBTEXT1=189
typeset -g POWERLEVEL9K_CATPPUCCIN_SUBTEXT0=102
typeset -g POWERLEVEL9K_CATPPUCCIN_OVERLAY2=102
typeset -g POWERLEVEL9K_CATPPUCCIN_OVERLAY1=102
typeset -g POWERLEVEL9K_CATPPUCCIN_OVERLAY0=59
typeset -g POWERLEVEL9K_CATPPUCCIN_SURFACE2=59
typeset -g POWERLEVEL9K_CATPPUCCIN_SURFACE1=59
typeset -g POWERLEVEL9K_CATPPUCCIN_SURFACE0=59
typeset -g POWERLEVEL9K_CATPPUCCIN_BASE=235
typeset -g POWERLEVEL9K_CATPPUCCIN_MANTLE=234
typeset -g POWERLEVEL9K_CATPPUCCIN_CRUST=233

# Apply Catppuccin colors to Powerlevel10k elements
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_BLUE
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$POWERLEVEL9K_CATPPUCCIN_BASE
typeset -g POWERLEVEL9K_DIR_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_BLUE
typeset -g POWERLEVEL9K_DIR_BACKGROUND=$POWERLEVEL9K_CATPPUCCIN_SURFACE0
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_GREEN
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$POWERLEVEL9K_CATPPUCCIN_SURFACE0
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_YELLOW
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$POWERLEVEL9K_CATPPUCCIN_SURFACE0
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_RED
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$POWERLEVEL9K_CATPPUCCIN_SURFACE0
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_GREEN
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$POWERLEVEL9K_CATPPUCCIN_RED
